---
- hosts: testserver
  become: true
  tasks:
  - name: yum update
    command: sudo yum update

  - name: Install docker
    command: sudo yum install -y docker-ce

  - name: Start docker service
    command: sudo systemctl start docker

  - name: Deploy insureme application
    command: sudo docker run -itd -p 8081:8081 --name insure-me mohandocker8/insure-me:3.0
